### ISSUE TITLE
Adding an apt-key for additional repositories.

### ISSUE THREAD

**Issue by rhauns** [stmork/kvm-hostcreator#9]
Adding additional apt-sources can be done in the raw copy stage simply by placing a _my-apt-source.conf_ file under _/root/deboot/etc/apt/sources.list.d_.  
But how to properly add the apt-key needed for my repo? I think this has to be done in the chrooted environment, so the postunpacking stage seems not the right place as stated in the README.  
Since  _apt update, apt dist-upgrade_ is called from the _install.sh_ inside the chrooted environment, the _gpg --recv-key, gpg --export, apt key-add_ must take place before running the _install.sh_ to prevent apt's repository is not signed error.  
Maybe another pre-install hook-script should be added?

**Comment by stmork** [comment]
The _apt-key_ usage in Ubuntu/Debian distros has been deprecated. You have to download the key files into the target's _/etc/apt/trusted.gpg.d/_ folder and have to reference it in the sources definition file like that (all from target's point of view):

`deb [signed-by=/etc/apt/trusted.gpg.d/example.gpg] http://<...>`

I suggest you to prepare the necessary key files from the hosts point of view into the _/root/deboot/_ folder in the _/etc/hostcreator/postunpack.sh_ stage.

**Comment by stmork** [comment]
If you agree I will correct the README file accordingly.

**Comment by rhauns** [comment]
Thats it. And also explains the ``usage of apt-key is deprecated`` message, i got indeed.  
Lazy people like me (hope i'm not the only one) first cry for help before doing some research on my own.  
Thanks a lot!
